### ISSUE TITLE
Failed to download asset

### ISSUE THREAD

**Issue by pkejval** [pannal/subsyncdkr#1]
Hello, when running

`docker run -it -v /mnt/data/torrent:/mnt/data/torrent pannal/subsyncdkr:latest sync --sub "${file%.*}.srt" --ref "$file" --out "${file%.*}.srt" --sub-lang=cze --overwrite`

it gives me error:
```
[+] downloading dictionary Czech / English   0%: 0.0 B / 1.1 MB                                                         12:09:46.439:     Download:    ERROR:  subsync.assets.downloader: updater failed
Traceback (most recent call last):
  File "subsync/assets/downloader.py", line 164, in _run
  File "subsync/assets/downloader.py", line 237, in _verify
  File "subsync/pubkey.py", line 24, in verify_crypto
FileNotFoundError: [Errno 2] No such file or directory: '/app/key.pub'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "subsync/assets/downloader.py", line 166, in _run
subsync.error.Error: Signature verification failed
asset:  dict/cze-eng
url:    https://github.com/sc0ty/subsync/releases/download/assets/dict-cze-eng.zip

[!] Signature verification failed
[-] asset: dict/cze-eng
[-] url: https://github.com/sc0ty/subsync/releases/download/assets/dict-cze-eng.zip
```

How to resolve? Where can I obtain '/app/key.pub'?

**Comment by pannal** [comment]
Can you try entering the container and copying or symlinking /app/subsync/key.pub to /app? If that fixes it I'll push a new version.

**Comment by pkejval** [comment]
Yes symlinking /key.pub to /app/key.pub works! :)
PS: There is no /app/subsync/key.pub

**Comment by pkejval** [comment]
There was another problem. Assets were downloaded (30-40 MB) each time `docker run -it pannal/subsyncdkr:latest` was run.
I fixed it by setting persistent storage for assets. This is my working command `docker run -it -v /mnt/data/torrent:/mnt/data/torrent -v /mnt/data/key.pub:/app/key.pub -v /mnt/data/assets:/root/.config/subsync/assets pannal/subsyncdkr:latest sync ...`

Attached file key.pub which is missing in container. I got it from subsync desktop app.
[key.zip](https://github.com/pannal/subsyncdkr/files/7329628/key.zip)
